name: Run Tests with Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run pytest in container
        run: docker compose run --rm web pytest